w10d01/demo/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # root "todos#index"

  # resources :todos

  # resources :characters

  # resources :locations

  resources :characters do
    resources :locations
  end
end

w10d01/demo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

w10d01/demo/app/models/character.rb
class Character < ApplicationRecord
  validates :name, presence: true

  has_many :locations # char.locations
end

w10d01/demo/app/models/location.rb
class Location < ApplicationRecord
  validates :location, presence: true
  validates :quote, presence: true

  belongs_to :character # location.character
end

w10d01/demo/app/models/todo.rb
class Todo < ApplicationRecord
  validates :task, presence: true, length: { minimum: 8 }
end

w10d01/demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

w10d01/demo/app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def index
    @characters = Character.all

    # render 'index'
    render json: @characters
  end

end

w10d01/demo/app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    character_id = params[:character_id]
    @character = Character.find character_id
    @locations = @character.locations

    render json: {
      character: @character,
      locations: @locations
    }
  end

end

w10d01/demo/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to [:todos], notice: 'created'
    else
      render :new, status: :not_found
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:task)
  end
end

w10d01/demo/app/helpers/application_helper.rb
module ApplicationHelper
end

w10d01/demo/app/helpers/characters_helper.rb
module CharactersHelper
end

w10d01/demo/app/helpers/locations_helper.rb
module LocationsHelper
end

w10d01/demo/app/helpers/todos_helper.rb
module TodosHelper
end

w10d01/demo/app/views/characters/index.html.erb
<h1>All the characters!</h1>

<% @characters.each do |character| %>
  <div class="character">
    <h2>Name: <%= character.name %></h2>
    <%= link_to "This characters locations", character_locations_path(character) %>
  </div>
<% end %>

w10d01/demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

w10d01/demo/app/views/locations/index.html.erb
<h1>All the locations for <%= @character.name %>!</h1>

<% @locations.each do |location| %>
  <div class="location">
    <h2>Location: <%= location.location %></h2>
    <h2>Quote: <%= location.quote %></h2>
    <h2>Character: <%= location.character.name %></h2>
  </div>
<% end %>

w10d01/demo/app/views/todos/index.html.erb
<h1>All the todos!</h1>

<%= link_to "Create a new todo!", [:new, :todo] %>

<ul>
  <% @todos.each do |todo| %>
    <li><%= todo.task %> (<%= todo.is_complete %>)</li>
  <% end %>
</li>

w10d01/demo/app/views/todos/new.html.erb
<h1>Create a new todo!</h1>

<%= link_to "Go back", [:todos] %>

<%= form_with(model: @todo, local: true) do |form| %>
  <% if @todo.errors.any? %>
    <div>
      <h2><%= pluralize(@todo.errors.count, "error") %> prevented us from creating a todo. Do better senator!</h2>
      <ul>
        <% @todo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :task %>
  <%= form.text_field :task %>

  <%= form.submit %>
<% end %>